#Project Work!


The project work is:

Try different MLP models on you own dataset. You have to find a dataset than can be used during the home project. That means you have to search for a dataset in the web. 

You have to introduce the dataset - what is its properties and main characteristics.

Also describe the problem type that is solved by using the dataset (classification or regression).

Grading:
-For grade 3 it is enough to try the next code snippet with your own dataset, describe the properties of the dataset and introduce the model performace. 

For greater grades please try more models and determine which model is the best according to the applied metrics.

Necessary: you can use this colab notebook as a basis for your homework. Notes can be done within the notebook or in a separated document.

After doing the home project, the notebook should be sent to: denes-fazakas.lehel@uni-obuda.hu

If you want to use MATLAB, that is also possible - in this case, you should implement the program code from here in MATLAB. 

Due date: May 2, 12.00

In case of any questions or if you need help - let me know via the given email address.

Lehel Dénes-Fazakas

In [4]:
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_openml
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import confusion_matrix
import numpy as np

#print(doc)


# Load data from https://www.openml.org/d/554
X, y = fetch_openml('mnist_784', version=1, return_X_y=True)
X = X / 255.


# rescale the data, use the traditional train/test split
X_train, X_test = X[:60000], X[60000:]
y_train, y_test = y[:60000], y[60000:]


#We create a MLP network with 784 features coming from pixels and one hidden layer with dimension of 50 and an output 
# layer with 10 outputs (digits) [0,9]. Activation function is relu
mlp = MLPClassifier(hidden_layer_sizes=(50,), max_iter=10, alpha=1e-4,
                    solver='sgd', verbose=10,activation='relu', random_state=1,
                    learning_rate_init=.1)


mlp.fit(X_train, y_train)
print("Training set score: %f" % mlp.score(X_train, y_train))
print("Test set score: %f" % mlp.score(X_test, y_test))


y_pre = mlp.predict(X_test)


accuracy = accuracy_score(y_test, y_pre)
print('Accuracy: %f' % accuracy)
for i in np.unique(y_test):
    ytest = []
    ypre = []
    for y in y_test:
        if (y == i):
            ytest.append(1)
        else:
            ytest.append(0)
    for y in y_pre:
        if (y == i):
            ypre.append(1)
        else:
            ypre.append(0)


#precision tp / (tp + fp)
precision = precision_score(ytest, ypre)
print(i + ' Precision: %f' % precision)
# recall: tp / (tp + fn)
recall = recall_score(ytest, ypre)
print(i+' Recall: %f' % recall)
# f1: 2 tp / (2 tp + fp + fn)
f1 = f1_score(ytest, ypre)
print(i + ' F1 score: %f' % f1)
matrix = confusion_matrix(y_test, y_pre)
print(matrix)

Iteration 1, loss = 0.32009978
Iteration 2, loss = 0.15347534
Iteration 3, loss = 0.11544755
Iteration 4, loss = 0.09279764
Iteration 5, loss = 0.07889367
Iteration 6, loss = 0.07170497
Iteration 7, loss = 0.06282111
Iteration 8, loss = 0.05530788
Iteration 9, loss = 0.04960484
Iteration 10, loss = 0.04645355


c:\users\anderu\pycharmprojects\islabs\venv\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(


Training set score: 0.986800
Test set score: 0.970000
Accuracy: 0.970000
9 Precision: 0.947927
9 Recall: 0.974232
9 F1 score: 0.960899
[[ 962    0    2    1    0    4    3    2    2    4]
 [   0 1119    5    3    0    0    3    1    4    0]
 [   5    1  991   10    4    0    5   11    4    1]
 [   0    0    6  978    1    9    0    7    1    8]
 [   1    0    3    1  948    0    6    5    0   18]
 [   2    0    1    9    1  857    8    3    7    4]
 [   5    3    2    1    5    4  938    0    0    0]
 [   0    1    5    8    1    0    0 1002    0   11]
 [   7    0    3   18    3    5    4    4  922    8]
 [   2    2    0    4    8    3    0    6    1  983]]
